### ISSUE TITLE
Window closing after new file is created

### ISSUE THREAD

**Issue by th4lmain** [TS-Tobias/obsidian-no-tabs#2]
Whenever I create a new file in Obsidian using the quick switcher (ie. opening the quick switcher, typing in a file name, and pressing enter/shift + enter) it creates and opens the new file in the active window, then immediately closes. The file is created and I can reopen and use the new file regularly. Notably this bug does not occur when using the "new file" command directly, just creating a new file from the quick switcher. After playing with my plugins, I found this plugin to be the source of this bug. Disabling your plugin stopped the issue without reloading or restarting Obsidian. Reenabling your plugin brought the issue back, again without reloading or restarting Obsidian.

I use Obsidian on an Intel 2020 Macbook pro (macOS 13.4.1). I use obsidian 1.4.13. Active plugins below. They are all up to date as of 5 minutes ago.

Admonition
Advanced Tables
Annotator
Auto Link Title
Better Word Count
Chem
Desmos
Editor Syntax Highlight
Excalidraw
Execute Code
Extended MathJax
Filename Heading Sync
Fullscreen mode plugin
Global Search and Replace
Hider
Hotkey Helper
Hotkeys++
Linter
MathJax Wikilinks
Media Extended
No Tabs
Obsidian MtG
Pandoc Plugin
Paste URL into selection
PDF Highlights
Regex Find/Replace
Remember cursor position
Select current line
Settings Search
Smarter Markdown Hotkeys
Sort & Permute lines
Text Extractor
Text Format
TikZJax
Typewriter Scroll

**Comment by TS-Tobias** [comment]
The Obsidian team recently added a hotkey to the application that makes this extension obsolete. The new hotkey is called `Create new note in current tab` and you can enable it in the settings. You can set this new hotkey to `cmd` + `n` and remove the binding from `Create new note` to replace this extension and avoid compatibility issues.

As a consequence, I have stopped the development of this extension. I have updated the README to reflect this change and I am working to remove the extension from the store as soon as possible.
